#!/usr/bin/env node
/**
 * Data Academy — production build
 * Usage: node build.js
 * Output: dist/  (upload its contents to the web root)  +  Academy-build-<date>.zip
 *
 * Steps: copy site files → minify CSS/JS (esbuild) → bump ?v= cache-buster
 *        → write production .htaccess → zip.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = __dirname;
const DIST = path.join(ROOT, 'dist');
// Forward slashes survive the node → cmd → PowerShell hand-off; .NET accepts them on Windows.
const ps = (p) => p.split(path.sep).join('/');
const DIST_PS = ps(DIST);
const VERSION = new Date().toISOString().slice(0, 10).replace(/-/g, '');

const FILES = [
  'index.html',
  'ar/index.html',
  'contact.php',
  'assets/css/style.css',
  'assets/js/main.js',
  'assets/img/logo.png',
];

function copy(rel) {
  const src = path.join(ROOT, rel);
  const dst = path.join(DIST, rel);
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  fs.copyFileSync(src, dst);
}

function esbuild(args) {
  execSync(`npx --yes esbuild ${args}`, { cwd: ROOT, stdio: ['ignore', 'pipe', 'inherit'] });
}

function size(rel) {
  return fs.statSync(path.join(DIST, rel)).size;
}

console.log(`Building Data Academy → dist/  (version ${VERSION})`);

// 1) Clean + copy
fs.rmSync(DIST, { recursive: true, force: true });
FILES.forEach(copy);

// 2) Minify CSS and JS in place
esbuild(`assets/css/style.css --minify --outfile=dist/assets/css/style.css --allow-overwrite --log-level=warning`);
esbuild(`assets/js/main.js --minify --target=es2017 --outfile=dist/assets/js/main.js --allow-overwrite --log-level=warning`);

// 3) Bump cache-busting query and strip blank-line runs in HTML (keeps markup readable & diffable)
for (const rel of ['index.html', 'ar/index.html']) {
  const p = path.join(DIST, rel);
  let html = fs.readFileSync(p, 'utf8');
  html = html.replace(/(style\.css|main\.js)\?v=\d+/g, `$1?v=${VERSION}`);
  html = html.replace(/\n{3,}/g, '\n\n');
  fs.writeFileSync(p, html);
}

// 4) Production .htaccess
fs.writeFileSync(path.join(DIST, '.htaccess'), `# Data Academy — production .htaccess (generated by build.js)
DirectoryIndex index.html index.php
Options -Indexes
AddDefaultCharset UTF-8

# --- Force HTTPS + canonical host (enable once the SSL certificate is installed) ---
# <IfModule mod_rewrite.c>
#   RewriteEngine On
#   RewriteCond %{HTTPS} off [OR]
#   RewriteCond %{HTTP_HOST} ^www\. [NC]
#   RewriteRule ^ https://thedataacademy.com%{REQUEST_URI} [L,R=301]
# </IfModule>

# --- Clean URLs: /index.html -> /  and  /ar/index.html -> /ar/ ---
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{THE_REQUEST} \\s/(.*/)?index\\.html[\\s?] [NC]
  RewriteRule ^(.*/)?index\\.html$ /%1 [R=301,L]
</IfModule>

# --- Compression ---
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css text/plain text/xml application/javascript application/json image/svg+xml
</IfModule>

# --- Browser caching (assets are cache-busted with ?v=) ---
<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType text/css "access plus 1 year"
  ExpiresByType application/javascript "access plus 1 year"
  ExpiresByType image/png "access plus 1 year"
  ExpiresByType image/svg+xml "access plus 1 year"
  ExpiresByType text/html "access plus 1 hour"
</IfModule>

# --- Security headers ---
<IfModule mod_headers.c>
  Header set X-Content-Type-Options "nosniff"
  Header set X-Frame-Options "SAMEORIGIN"
  Header set Referrer-Policy "strict-origin-when-cross-origin"
  Header set Permissions-Policy "camera=(), microphone=(), geolocation=()"
</IfModule>

# --- Protect the request log written by contact.php ---
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteRule ^storage/ - [F,L]
</IfModule>
<FilesMatch "\.(log|md|json)$">
  Require all denied
</FilesMatch>
`);

// 5) Zip
const zipName = `Academy-build-${VERSION}.zip`;
const zipPath = path.join(ROOT, zipName);
fs.rmSync(zipPath, { force: true });
execSync(
  `powershell -NoProfile -Command "Compress-Archive -Path '${DIST_PS}/*' -DestinationPath '${ps(zipPath)}' -Force"`,
  { stdio: 'inherit' }
);
// 6) Report
const kb = (n) => (n / 1024).toFixed(1) + ' KB';
console.log('\nOutput:');
for (const rel of [...FILES, '.htaccess']) {
  const orig = rel === '.htaccess' ? 0 : fs.statSync(path.join(ROOT, rel)).size;
  console.log(`  ${rel.padEnd(24)} ${kb(orig).padStart(9)} → ${kb(size(rel)).padStart(9)}`);
}
console.log(`\n  ${zipName}  ${kb(fs.statSync(zipPath).size)}`);
console.log('\nUpload the contents of dist/ (or unzip the archive) into the web root.');
